### PR TITLE
Fix for string values that contain double quotes

### PR DESCRIPTION
**Pull request by seco560**
I encountered an issue using this package wherein the generated JSON did not properly escape double quotes. I wrote a very small amount of code, but from my limited testing it seems to do the job of properly escaping double quotes. I also modified an assignment statement as per recommendation from the Kotlin static analyzer.
If there is still anyone actively maintaining this project, please take a look at my meager pull request and if all is well please merge it into the main repo. Thank you and happy programming.

### CODE REVIEW

**Comment by VaishnavDatir** [comment]
PR in review.

**Comment by VaishnavDatir** [comment]
Looks good to me.
@seco560 thanks for your contribution and efforts.
Will merge this into master branch after testing few things.

**Comment by seco560** [comment]
I appreciate it, thank you. But you never merged the pr_zone branch back into master, which means the changes aren't published into pub.dev. If you'd like to see them reflected there, please do a merge into master. As of now I'm still using the fork I made on my own GitHub page.

**Comment by VaishnavDatir** [comment]
Hi @seco560,

Sure. Don't worry will get it merged in master branch. I am still doing some R&D on the plugin to increase the usability, performance and etc.
Will let you know once it is merged.

Thanks

**Pull request merged**
